name: cd

on:
  release:
    types: [published]

jobs:
  hex-publish:
    uses: straw-hat-team/github-actions-workflows/.github/workflows/elixir-hex-publish.yml@v1.3.0
    secrets:
      HEX_API_KEY: ${{ secrets.HEX_API_KEY }}
